name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack --no-restore -c Release --output .
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/CommonLib/SharpHoundCommonLib.csproj
        PACKAGE_NAME: SharpHoundCommon
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
  docs:
    name: docs
    runs-on: windows-latest
    steps:
      # Check out the branch that triggered this workflow to the 'source' subdirectory
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install DocFX
        run: "& choco install docfx -y"
      - name: Clear ./docs
        working-directory: ./docs
        run: DEL /S /Q *.TMP
      - name: Run DocFX
        run: docfx docfx.json
        # update docs
      - name: Commit to master and push
        run: |
          $ErrorActionPreference = "Continue"
          git add -A
          git diff HEAD --exit-code
          if ($LASTEXITCODE -eq 0) {
            Write-Host "No changes to commit!"
          } else {
            git config --global user.name "github-actions-docfx[bot]"
            git config --global user.email "ari@thirteendelta.com"
            git commit -m "Updated docs from commit $env:GITHUB_SHA on $env:GITHUB_REF"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push origin master
          }
        working-directory: ./docs
